name: sys2bench
channels:
  - nvidia/label/cuda-12.1.1
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blessed=1.20.0=py310h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.1.31=hbcca054_0
  - cuda-compiler=12.1.1=0
  - cuda-cuobjdump=12.1.111=0
  - cuda-cuxxfilt=12.1.105=0
  - cuda-nvcc=12.1.105=0
  - cuda-nvprune=12.1.105=0
  - gpustat=1.1.1=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.4.1=h7b32b05_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tmux=3.4=hb25038b_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.8.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiohttp-cors==0.8.0
      - aiosignal==1.3.1
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anthropic==0.34.2
      - antlr4-python3-runtime==4.7.2
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astor==0.8.1
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bitsandbytes==0.43.3
      - blake3==1.0.4
      - bleach==6.2.0
      - blobfile==3.0.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - colorful==0.5.6
      - comm==0.2.2
      - compressed-tensors==0.10.2
      - contourpy==1.3.1
      - cryptography==45.0.2
      - cuda-bindings==12.9.0
      - cuda-python==12.9.0
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - datasets==3.1.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - deepspeed==0.15.4
      - defusedxml==0.7.1
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fairscale==0.4.13
      - fastapi==0.115.11
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.2
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fire==0.6.0
      - flash-attn==2.8.1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.19.2
      - google-api-python-client==2.143.0
      - google-auth==2.34.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.1
      - grpcio-status==1.62.3
      - h11==0.14.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.33.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.8
      - importlib-metadata==8.6.1
      - interegular==0.3.3
      - ipykernel==6.29.5
      - ipython==8.35.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.5.0
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lark-parser==0.12.0
      - llama-models==0.0.13
      - llama-toolchain==0.0.13
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.7.0
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - notebook==7.4.0
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvshmem-cu12==3.3.9
      - nvidia-nvtx-cu12==12.8.55
      - omegaconf==2.3.0
      - openai==1.66.3
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - optimum==1.21.4
      - outlines==0.1.11
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post5
      - pddl==0.2.0
      - peft==0.12.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - prompt-toolkit==3.0.50
      - proto-plus==1.24.0
      - protobuf==4.25.4
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pybase64==1.4.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2024.1
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - ray==2.43.0
      - referencing==0.36.2
      - regex==2024.7.24
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rich-toolkit==0.14.8
      - rignore==0.5.1
      - rpds-py==0.23.1
      - rsa==4.9
      - safetensors==0.4.5
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.24.0
      - setproctitle==1.3.5
      - setuptools==70.2.0
      - shellingham==1.5.4
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.46.1
      - sympy==1.14.0
      - tarski==0.8.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tornado==6.4.2
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.53.1
      - triton==3.3.0
      - trl==0.19.1
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==2.2.2
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.3
      - vllm==0.9.2
      - wandb==0.19.8
      - watchfiles==1.0.4
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xxhash==3.5.0
      - yarl==1.9.11
      - zipp==3.21.0
variables:
  PYTHONPATH: '/data/shurui.gui/Projects/Sys2Bench:'
  CPATH: '/data/shurui.gui/mambaforge/envs/sys2bench/lib/python3.10/site-packages/triton/backends/nvidia/include:/data/shurui.gui/mambaforge/envs/sys2bench/lib/python3.10/site-packages/nvidia/cuda_runtime/include:'
prefix: /data/shurui.gui/mambaforge/envs/sys2bench
