name: Blocksworld

args:

  path: divelab/blocksworld
  train_levels: 
    - 0
    - 1
    - 2
    - 3
  test_levels:
    - 0
    - 1
    - 2
    - 3
    - 4

  system_content: "You are a helpful assistant. You first think about the reasoning process in the mind and then provides the user with the answer.\n"
  user_content: "I am playing with a set of blocks where I need to arrange the blocks into stacks. Here are the actions I can do\n
   \n
   Pick up a block\n
   Unstack a block from on top of another block\n
   Put down a block\n
   Stack a block on top of another block\n
   \n
   I have the following restrictions on my actions:\n
   I can only pick up or unstack one block at a time.\n
   I can only pick up or unstack a block if my hand is empty.\n
   I can only pick up a block if the block is on the table and the block is clear.\n
   A block is clear if the block has no other blocks on top of it and if the block is not picked up.\n
   I can only unstack a block from on top of another block if the block I am unstacking was really on top of the other block.\n
   I can only unstack a block from on top of another block if the block I am unstacking is clear.\n
   Once I pick up or unstack a block, I am holding the block.\n
   I can only put down a block that I am holding.\n
   I can only stack a block on top of another block if I am holding the block being stacked.\n
   I can only stack a block on top of another block if the block onto which I am stacking the block is clear.\n
   Once I put down or stack a block, my hand becomes empty.\n
   \n
   Here is the format of the actions:\n 
   pick up the [block_name] block\n
   unstack the [block_name] block from on top of the [another_block_name] block\n
   put down the [block_name] block\n
   stack the [block_name] block on top of the [another_block_name] block\n
   \n
   [Problem]\n
   Here is the initial state of the blocks: {question}\n
   Here is the goal state of the blocks: {answer}. Show your work in <think> </think> tags. After that, provide the final answer in <answer> </answer> tags, for example:\n
   <answer>\n
   unstack the cyan block from on top of the emerald block\n
   put down the cyan block\n
   </answer>\n"
  assistant_content: "Let me solve this step by step.\n<think>"

  format_reward: 1.0
  format_reward_fn: FormatReward
  correctness_reward: 2.0
  correctness_reward_fn: BlocksworldCorrectnessReward

  max_steps: 1200
  max_prompt_length: 1600
  max_completion_length: 512